# combine all the dictaonry old , new(if added ) to make final dictonary


bad_words_dict1 = {
    "damn": ["unfortunate", "regrettable", "undesirable", "disappointing", "annoying"],
    "bad": ["unfavorable", "poor", "suboptimal", "deficient", "inadequate"],
    "shit": ["nonsense", "rubbish", "balderdash", "problem", "difficulty"],
    "****": ["unacceptable", "inappropriate", "offensive", "objectionable", "vulgar"],
    "bitch": [
        "unpleasant person",
        "difficult individual",
        "obnoxious person",
        "mean-spirited person",
        "aggressive individual",
    ],
    "asshole": [
        
        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "self-centered person",
    ],
    "fuck": ["mess", "problem", "inconvenience", "difficulty"],
    "crap": ["nonsense", "rubbish", "poor quality", "inferior", "substandard"],
    "hell": [
        "difficult situation",
        "challenging time",
        "frustrating experience",
        "unpleasant ordeal",
        "trying period",
    ],
    "stupid": ["unwise", "foolish", "misguided", "lacking judgment", "shortsighted"],
    "idiot": [
        "fool",
        "simpleton",
        "uninformed person",
        "naïve individual",
        "unintelligent person",
    ],
    "moron": [
        "fool",
        "simpleton",
        "uninformed person",
        "naïve individual",
        "unintelligent person",
    ],
    "ass": ["rear", "buttocks", "inconsiderate person",  "stubborn person"],
    "dick": [
        
        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "obnoxious person",
    ],
    "bastard": [
        "unfortunate person",
        "illegitimate",
        "difficult person",
        
        "unpleasant individual",
    ],
    "bimbo": [
        "airhead",
        "ditzy",
        "uninformed person",
        "naïve individual",
        "frivolous person",
    ],
    "slut": ["promiscuous", "loose", "immoral", "sexually active", "unchaste"],
    "whore": [
        "prostitute",
        "sex worker",
        "promiscuous person",
        "loose woman",
        "commercial sex worker",
    ],
    "fool": [
        "dupe",
        "simpleton",
        "naïve person",
        "easily deceived person",
        "gullible person",
    ],
    "cunt": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "piss": ["urine", "annoy", "irritate", "frustrate", "aggravate"],
    "cock": ["rooster", "penis",  "inconsiderate person", "arrogant person"],
    "douche": [
        "douchebag",
        
        "inconsiderate person",
        "obnoxious person",
        "arrogant person",
    ],
    "fag": [
        "offensive term",
        "homosexual",
        "gay man",
        "queer person",
        "same-sex attracted individual",
    ],
    "gay": [
        "homosexual",
        "same-sex attracted",
        "LGBTQ+",
        "non-heterosexual",
        "homophilic",
    ],
    "lesbian": [
        "homosexual woman",
        "same-sex attracted woman",
        "LGBTQ+",
        "non-heterosexual woman",
        "homophilic woman",
    ],
    "retard": [
        "offensive term",
        "developmentally delayed",
        "intellectually disabled",
        "special needs",
        "cognitively impaired",
    ],
    "nigger": [
        "offensive term",
        "black person",
        "African American",
        "person of African descent",
        "individual of African heritage",
    ],
    "kike": [
        "offensive term",
        "Jewish person",
        "Jew",
        "member of the Jewish faith",
        "individual of Jewish heritage",
    ],
    "chink": [
        "offensive term",
        "Chinese person",
        "person of Chinese descent",
        "East Asian person",
        "individual of Chinese heritage",
    ],
    "spic": [
        "offensive term",
        "Hispanic person",
        "Latino/a person",
        "person of Latin American descent",
        "individual of Latin American heritage",
    ],
    "gook": [
        "offensive term",
        "Asian person",
        "person of Asian descent",
        "East Asian person",
        "individual of Asian heritage",
    ],
    "raghead": [
        "offensive term",
        "Middle Eastern person",
        "South Asian person",
        "person of Middle Eastern/South Asian descent",
        "individual of Middle Eastern/South Asian heritage",
    ],
    "camel jockey": [
        "offensive term",
        "Arab person",
        "Middle Eastern person",
        "person of Arab descent",
        "individual of Arab heritage",
    ],
    "sand nigger": [
        "offensive term",
        "Arab person",
        "Middle Eastern person",
        "person of Arab descent",
        "individual of Arab heritage",
    ],
    "honky": [
        "offensive term",
        "white person",
        "Caucasian person",
        "person of European descent",
        "individual of European heritage",
    ],
    "cracker": [
        "offensive term",
        "white person",
        "Caucasian person",
        "person of European descent",
        "individual of European heritage",
    ],
    "redneck": [
        "rural person",
        "country person",
        "working-class person",
        "Southern person",
        "provincial individual",
    ],
    "hillbilly": [
        "rural person",
        "country person",
        "mountain person",
        "backwoods person",
        "rustic individual",
    ],
    "wetback": [
        "offensive term",
        "Mexican person",
        "Latino/a person",
        "person of Mexican descent",
        "individual of Mexican heritage",
    ],
    "mick": [
        "offensive term",
        "Irish person",
        "person of Irish descent",
        "Celtic person",
        "individual of Irish heritage",
    ],
    "polack": [
        "offensive term",
        "Polish person",
        "person of Polish descent",
        "Eastern European person",
        "individual of Polish heritage",
    ],
    "greaseball": [
        "offensive term",
        "Italian person",
        "person of Italian descent",
        "Mediterranean person",
        "individual of Italian heritage",
    ],
    "dyke": [
        "offensive term",
        "lesbian",
        "homosexual woman",
        "same-sex attracted woman",
        "homophilic woman",
    ],
    "bastard": [
        "illegitimate",
        "difficult person",
        "unfortunate person",
        "unpleasant individual",
    ],
    "motherfucker": [

        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "obnoxious person",
    ],
    "son of a bitch": [

        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "obnoxious person",
    ],
    "cock sucker": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "ass wipe": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "fucking": ["extremely", "very", "really", "intensely", "remarkably"],
    "shithead": [
        "idiot",
        "fool",

        "inconsiderate person",
        "unintelligent person",
    ],
    "dickhead": [
        "idiot",
        "fool",

        "inconsiderate person",
        "unintelligent person",
    ],
    "twat": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "pussy": ["cat", "kitten", "coward", "weakling", "timid person"],
    "clit": [
        "clitoris",
        "female genitalia",
        "vulva",
        "intimate area",
        "anatomical feature",
    ],
    "ball sack": [
        "scrotum",
        "testicles",
        "male genitalia",
        "intimate area",
        "anatomical feature",
    ],
    "testicles": [
        "testes",
        "male reproductive organs",
        "gonads",
        "intimate area",
        "anatomical feature",
    ],
    "tits": ["breasts", "boobs", "bosom", "chest", "anatomical feature"],
    "boobs": ["breasts", "tits", "bosom", "chest", "anatomical feature"],
    "nipples": [
        "areola",
        "mammary papilla",
        "breast tip",
        "chest",
        "anatomical feature",
    ],
    "vagina": [
        "vulva",
        "female genitalia",
        "birth canal",
        "intimate area",
        "anatomical feature",
    ],
    "penis": [
        "male genitalia",
        "phallus",
        "organ",
        "intimate area",
        "anatomical feature",
    ],
    "ejaculate": [
        "semen",
        "sperm",
        "sexual fluid",
        "bodily fluid",
        "reproductive fluid",
    ],
    "orgasm": [
        "climax",
        "sexual peak",
        "sexual pleasure",
        "intense sensation",
        "culmination",
    ],
    "masturbate": [
        "self-pleasure",
        "self-stimulation",
        "manual stimulation",
        "intimate act",
        "private act",
    ],
    "jerk off": [
        "masturbate",
        "self-pleasure",
        "self-stimulation",
        "manual stimulation",
        "private act",
    ],
    "cum": ["semen", "sperm", "ejaculate", "sexual fluid", "reproductive fluid"],
    "fuckface": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "butthole": [
        "anus",
        "rectum",
        "posterior opening",
        "bodily opening",
        "anatomical feature",
    ],
    "anal": [
        "rectal",
        "posterior",
        "pertaining to the anus",
        "bodily opening",
        "anatomical region",
    ],
    "porn": [
        "pornography",
        "adult entertainment",
        "erotica",
        "sexually explicit material",
        "adult content",
    ],
    "porno": [
        "pornography",
        "adult entertainment",
        "erotica",
        "sexually explicit material",
        "adult content",
    ],
    "sex": [
        "intercourse",
        "sexual activity",
        "sexual relations",
        "intimacy",
        "physical intimacy",
    ],
    "sexist": [
        "gender biased",
        "gender discriminatory",
        "prejudiced against women",
        "biased against a gender",
        "gender inequitable",
    ],
    "racist": [
        "racially biased",
        "racially discriminatory",
        "prejudiced against a race",
        "biased against a race",
        "racially inequitable",
    ],
    "homophobic": [
        "anti-gay",
        "prejudiced against homosexuals",
        "biased against LGBTQ+",
        "intolerant of homosexuality",
        "homo-antagonistic",
    ],
    "xenophobic": [
        "anti-foreigner",
        "prejudiced against foreigners",
        "biased against immigrants",
        "intolerant of foreigners",
        "xeno-antagonistic",
    ],
    "bigot": [
        "intolerant person",
        "prejudiced person",
        "biased person",
        "narrow-minded person",
        "dogmatic individual",
    ],
    "slutty": ["promiscuous", "loose", "immoral", "sexually active", "unchaste"],
    "whoring": [
        "prostitution",
        "promiscuity",
        "commercial sex",
        "sexual exploitation",
        "sexual commerce",
    ],
    "pimp": [
        "procurer",
        "exploiter",
        "profiteer",
        "trafficker",
        "facilitator of exploitation",
    ],
    "whorehouse": [
        "brothel",
        "house of prostitution",
        "bawdy house",
        "red-light district",
        "establishment of commercial sex",
    ],
    "brothel": [
        "whorehouse",
        "house of prostitution",
        "bawdy house",
        "red-light district",
        "establishment of commercial sex",
    ],
    "prostitute": [
        "sex worker",
        "commercial sex worker",
        "streetwalker",
        "escort",
        "sex trade worker",
    ],
    "escort": [
        "companion",
        "social escort",
        "dating partner",
        "paid companion",
        "commercial companion",
    ],
    "hooker": [
        "prostitute",
        "sex worker",
        "streetwalker",
        "commercial sex worker",
        "sex trade worker",
    ],
    "harlot": ["prostitute", "whore", "loose woman", "immoral woman", "unchaste woman"],
    "sugar daddy": [
        "wealthy benefactor",
        "older partner",
        "financial supporter",
        "generous patron",
        "patron of companionship",
    ],
    "gold digger": [
        "materialistic person",
        "opportunistic person",
        "fortune hunter",
        "financially motivated person",
        "materially driven individual",
    ],
    "sugar baby": [
        "younger partner",
        "beneficiary",
        "recipient of support",
        "compensated companion",
        "recipient of patronage",
    ],
    "mistress": [
        "lover",
        "paramour",
        "extramarital partner",
        "secret partner",
        "clandestine partner",
    ],
    "gigolo": [
        "male escort",
        "paid companion",
        "male prostitute",
        "kept man",
        "male commercial companion",
    ],
    "jigaboo": [
        "offensive term",
        "black person",
        "African American",
        "person of African descent",
        "individual of African heritage",
    ],
    "coon": [
        "offensive term",
        "black person",
        "African American",
        "person of African descent",
        "individual of African heritage",
    ],
    "asshat": [ "fool", "idiot", "inconsiderate person", "bonehead"],
}

bad_words_dict2 = {
    # Existing Entries...
    # Additional Entries
    # Personal Insults
    "moron": [
        "fool",
        "simpleton",
        "uninformed person",
        "naïve individual",
        "unintelligent person",
    ],
    # Body Parts and Related Terms
    "ass": ["rear", "buttocks", "inconsiderate person", "stubborn person"],
    # Derogatory Terms
    "dick": [
       
        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "obnoxious person",
    ],
    # Gender-Related Terms
    "bastard": [
        "illegitimate",
        "difficult person",
         
        "unfortunate person",
        "unpleasant individual",
    ],
    # Sexual Terms
    "slut": ["promiscuous", "loose", "immoral", "sexually active", "unchaste"],
    # Racial Slurs
    "nigger": [
        "offensive term",
        "black person",
        "African American",
        "person of African descent",
        "individual of African heritage",
    ],
    # Ethnic Slurs
    "kike": [
        "offensive term",
        "Jewish person",
        "Jew",
        "member of the Jewish faith",
        "individual of Jewish heritage",
    ],
    # General Insults
    "fool": [
        "dupe",
        "simpleton",
        "naïve person",
        "easily deceived person",
        "gullible person",
    ],
    # Cultural Insults
    "redneck": [
        "rural person",
        "country person",
        "working-class individual",
        "provincial individual",
        "southern individual",
    ],
    "redneck": [
        "rural person",
        "country person",
        "working-class individual",
        "provincial individual",
        "southern individual",
    ],
    "whore": [
        "prostitute",
        "sex worker",
        "promiscuous individual",
        "loose woman",
        "commercial sex worker",
    ],
    "dyke": [
        "offensive term",
        "lesbian",
        "homosexual woman",
        "same-sex attracted woman",
        "homophilic woman",
    ],
    "cunt": [
        "offensive term",
        "unpleasant individual",
        "vile individual",
        "despicable individual",
        "abhorrent individual",
    ],
    "cock": [
        "rooster",
        "penis",
        
        "inconsiderate individual",
        "arrogant individual",
    ],
    "douche": [
        "douchebag",
      
        "inconsiderate individual",
        "obnoxious individual",
        "arrogant individual",
    ],
    "fag": [
        "offensive term",
        "homosexual",
        "gay man",
        "queer individual",
        "same-sex attracted individual",
    ],
    "gay": [
        "homosexual",
        "same-sex attracted",
        "LGBTQ+",
        "non-heterosexual",
        "homophilic",
    ],
    "lesbian": [
        "homosexual woman",
        "same-sex attracted woman",
        "LGBTQ+",
        "non-heterosexual woman",
        "homophilic woman",
    ],
    "retard": [
        "offensive term",
        "developmentally delayed",
        "intellectually disabled",
        "special needs individual",
        "cognitively impaired",
    ],
    "chink": [
        "offensive term",
        "Chinese individual",
        "person of Chinese descent",
        "East Asian individual",
        "individual of Chinese heritage",
    ],
    "spic": [
        "offensive term",
        "Hispanic individual",
        "Latino/a individual",
        "person of Latin American descent",
        "individual of Latin American heritage",
    ],
    "gook": [
        "offensive term",
        "Asian individual",
        "person of Asian descent",
        "East Asian individual",
        "individual of Asian heritage",
    ],
    "camel jockey": [
        "offensive term",
        "Arab individual",
        "Middle Eastern individual",
        "person of Arab descent",
        "individual of Arab heritage",
    ],
    "honky": [
        "offensive term",
        "white individual",
        "Caucasian",
        "person of European descent",
        "individual of European heritage",
    ],
    "cracker": [
        "offensive term",
        "white individual",
        "Caucasian",
        "person of European descent",
        "individual of European heritage",
    ],
    "mick": [
        "offensive term",
        "Irish individual",
        "person of Irish descent",
        "Celtic",
        "individual of Irish heritage",
    ],
    "polack": [
        "offensive term",
        "Polish individual",
        "person of Polish descent",
        "Eastern European",
        "individual of Polish heritage",
    ],
    "greaseball": [
        "offensive term",
        "Italian individual",
        "person of Italian descent",
        "Mediterranean",
        "individual of Italian heritage",
    ],
    "bimbo": [
        "airhead",
        "ditzy",
        "uninformed individual",
        "naïve individual",
        "frivolous person",
    ],
    "sugar daddy": [
        "wealthy benefactor",
        "older partner",
        "financial supporter",
        "generous patron",
        "patron of companionship",
    ],
    "sugar baby": [
        "younger partner",
        "beneficiary",
        "recipient of support",
        "compensated companion",
        "recipient of patronage",
    ],
    "mistress": [
        "lover",
        "paramour",
        "extramarital partner",
        "secret partner",
        "clandestine partner",
    ],
    "gigolo": [
        "male escort",
        "paid companion",
        "male prostitute",
        "kept man",
        "male commercial companion",
    ],
    "whoring": [
        "prostitution",
        "promiscuity",
        "commercial sex",
        "sexual exploitation",
        "sexual commerce",
    ],
}
bad_words_dict4 = {
    "ass": ["behind"],
    "asshat": ["arrogant person"],
    "asswipe": ["irresponsible person", "disrespectful person"],
    "assclown": ["foolish person"],
    "assfucker": ["impolite person"],
    "assbuckets": ["foolish persons"],
    "asshole": ["person with bad manners"],
    "bastard": ["irresponsible person"],
    "bastards": ["unpleasant people"],
    "bastardy": ["irresponsible behavior"],
    "bastardization": ["deterioration"],
    "bitch": ["difficult person"],
    "bitchass": ["disrespectful person"],
    "bitching": ["complaining"],
    "bitchface": ["disrespectful person"],
    "bitchtastic": ["disrespectful person"],
    "bitchy": ["disrespectful"],
    "ballsack": ["male body part"],
    "buttface": ["silly person"],
    "buttmunch": ["foolish person"],
    "buttfuck": ["impolite phrase"],
    "buttfucker": ["impolite person"],
    "cock": ["male reproductive organ"],
    "cockblocker": ["person preventing action"],
    "cocky": ["overconfident"],
    "cockwomble": ["silly person"],
    "cocksniffer": ["foolish person"],
    "cocksucker": ["subservient person"],
    "crap": ["bad situation"],
    "crappy": ["inferior"],
    "craphead": ["disrespectful person"],
    "cum": ["sexual fluid"],
    "cumdumpster": ["derogatory term"],
    "cumslut": ["derogatory term"],
    "dick": ["male genitalia"],
    "dickbag": ["foolish person"],
    "dickhead": ["arrogant person"],
    "dickwit": ["irresponsible person"],
    "douche": ["impolite person"],
    "douchebag": ["self-centered person"],
    "douchecanoe": ["foolish person"],
    "douchepocket": ["irresponsible person"],
    "douchey": ["self-centered"],
    "dickwad": ["irresponsible person"],
    "dickface": ["impolite person"],
    "dickhead": ["arrogant person"],
    "douchebaggery": ["irresponsible behavior"],
    "dumb": ["unaware"],
    "fag": ["homophobic slur"],
    "faggot": ["homophobic slur"],
    "fake": ["insincere"],
    "freaking": ["intensifying"],
    "freakshow": ["unusual situation"],
    "fuck": ["mess"],
    "fucking": ["intense action"],
    "fuckery": ["misconduct"],
    "fucktard": ["irresponsible person"],
    "fuckface": ["impolite person"],
    "fuckwad": ["irresponsible person"],
    "fuckwit": ["irresponsible person"],
    "fleshlight": ["sex toy"],
    "fuckshit": ["disastrous situation"],
    "hell": ["difficult situation"],
    "hater": ["critical person"],
    "hateful": ["full of hate"],
    "hate": ["dislike"],
    "idiot": ["novice"],
    "idiotic": ["thoughtless"],
    "idiotproof": ["easy"],
    "incompetent": ["lacking ability"],
    "loser": ["underachiever"],
    "lowlife": ["underachiever"],
    "moron": ["beginner"],
    "moronic": ["foolish"],
    "misogynistic": ["sexist"],
    "motherfucker": ["irresponsible person"],
    "noob": ["beginner"],
    "nutsack": ["testicles"],
    "piss": ["urine"],
    "pisshead": ["unpleasant person"],
    "poop": ["feces"],
    "pussy": ["coward"],
    "prick": ["arrogant person"],
    "pricks": ["impolite persons"],
    "retard": ["slow learner"],
    "retarded": ["slow learner"],
    "retardation": ["slowness"],
    "slut": ["promiscuous person"],
    "slutbucket": ["derogatory term"],
    "slutface": ["disrespectful person"],
    "slutty": ["promiscuous"],
    "shit": ["easy work"],
    "shitass": ["unpleasant person"],
    "shitface": ["disrespectful person"],
    "shithead": ["unpleasant person"],
    "shitshow": ["disastrous event"],
    "shitstorm": ["chaotic situation"],
    "shitty": ["unpleasant"],
    "shitfaced": ["heavily intoxicated"],
    "shithole": ["bad place", "unpleasant place"],
    "smegma": ["body fluid"],
    "son of a bitch": ["disrespectful person"],
    "suck": ["underperform"],
    "suckmydick": ["disrespectful phrase"],
    "sucky": ["underwhelming"],
    "stfu": ["keep quiet"],
    "stinky": ["unpleasant odor"],
    "stupid": ["unintelligent"],
    "twat": ["silly person"],
    "twaddle": ["nonsense"],
    "twats": ["silly persons"],
    "toxic": ["unhealthy"],
    "weakling": ["fragile"],
    "whore": ["sex worker"],
    "whorebag": ["disrespectful person"],
    "whoreish": ["promiscuous"],
    "wanker": ["foolish person"],
}


bad_words_dict3 = {
    "damn": ["unfortunate", "regrettable", "undesirable", "disappointing", "annoying"],
    "bad": ["unfavorable", "poor", "suboptimal", "deficient", "inadequate"],
    "shit": ["nonsense", "rubbish", "balderdash", "problem", "difficulty"],
    "****": ["unacceptable", "inappropriate", "offensive", "objectionable", "vulgar"],
    "bitch": [
        "unpleasant person",
        "difficult individual",
        "obnoxious person",
        "mean-spirited person",
        "aggressive individual",
    ],
    "asshole": [
        
        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "self-centered person",
    ],
    "fuck": ["mess", "problem", "inconvenience", "difficulty"],
    "crap": ["nonsense", "rubbish", "poor quality", "inferior", "substandard"],
    "hell": [
        "difficult situation",
        "challenging time",
        "frustrating experience",
        "unpleasant ordeal",
        "trying period",
    ],
    "stupid": ["unwise", "foolish", "misguided", "lacking judgment", "shortsighted"],
    "idiot": [
        "fool",
        "simpleton",
        "uninformed person",
        "naïve individual",
        "unintelligent person",
    ],
    "moron": [
        "fool",
        "simpleton",
        "uninformed person",
        "naïve individual",
        "unintelligent person",
    ],
    "ass": ["rear", "buttocks", "inconsiderate person",  "stubborn person"],
    "dick": [
        
        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "obnoxious person",
    ],
    "bastard": [
        "unfortunate person",
        "illegitimate",
        "difficult person",
        
        "unpleasant individual",
    ],
    "bimbo": [
        "airhead",
        "ditzy",
        "uninformed person",
        "naïve individual",
        "frivolous person",
    ],
    "slut": ["promiscuous", "loose", "immoral", "sexually active", "unchaste"],
    "whore": [
        "prostitute",
        "sex worker",
        "promiscuous person",
        "loose woman",
        "commercial sex worker",
    ],
    "fool": [
        "dupe",
        "simpleton",
        "naïve person",
        "easily deceived person",
        "gullible person",
    ],
    "cunt": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "piss": ["urine", "annoy", "irritate", "frustrate", "aggravate"],
    "cock": ["rooster", "penis",  "inconsiderate person", "arrogant person"],
    "douche": [
        "douchebag",
        
        "inconsiderate person",
        "obnoxious person",
        "arrogant person",
    ],
    "fag": [
        "offensive term",
        "homosexual",
        "gay man",
        "queer person",
        "same-sex attracted individual",
    ],
    "gay": [
        "homosexual",
        "same-sex attracted",
        "LGBTQ+",
        "non-heterosexual",
        "homophilic",
    ],
    "lesbian": [
        "homosexual woman",
        "same-sex attracted woman",
        "LGBTQ+",
        "non-heterosexual woman",
        "homophilic woman",
    ],
    "retard": [
        "offensive term",
        "developmentally delayed",
        "intellectually disabled",
        "special needs",
        "cognitively impaired",
    ],
    "nigger": [
        "offensive term",
        "black person",
        "African American",
        "person of African descent",
        "individual of African heritage",
    ],
    "kike": [
        "offensive term",
        "Jewish person",
        "Jew",
        "member of the Jewish faith",
        "individual of Jewish heritage",
    ],
    "chink": [
        "offensive term",
        "Chinese person",
        "person of Chinese descent",
        "East Asian person",
        "individual of Chinese heritage",
    ],
    "spic": [
        "offensive term",
        "Hispanic person",
        "Latino/a person",
        "person of Latin American descent",
        "individual of Latin American heritage",
    ],
    "gook": [
        "offensive term",
        "Asian person",
        "person of Asian descent",
        "East Asian person",
        "individual of Asian heritage",
    ],
    "raghead": [
        "offensive term",
        "Middle Eastern person",
        "South Asian person",
        "person of Middle Eastern/South Asian descent",
        "individual of Middle Eastern/South Asian heritage",
    ],
    "camel jockey": [
        "offensive term",
        "Arab person",
        "Middle Eastern person",
        "person of Arab descent",
        "individual of Arab heritage",
    ],
    "sand nigger": [
        "offensive term",
        "Arab person",
        "Middle Eastern person",
        "person of Arab descent",
        "individual of Arab heritage",
    ],
    "honky": [
        "offensive term",
        "white person",
        "Caucasian person",
        "person of European descent",
        "individual of European heritage",
    ],
    "cracker": [
        "offensive term",
        "white person",
        "Caucasian person",
        "person of European descent",
        "individual of European heritage",
    ],
    "redneck": [
        "rural person",
        "country person",
        "working-class person",
        "Southern person",
        "provincial individual",
    ],
    "hillbilly": [
        "rural person",
        "country person",
        "mountain person",
        "backwoods person",
        "rustic individual",
    ],
    "wetback": [
        "offensive term",
        "Mexican person",
        "Latino/a person",
        "person of Mexican descent",
        "individual of Mexican heritage",
    ],
    "mick": [
        "offensive term",
        "Irish person",
        "person of Irish descent",
        "Celtic person",
        "individual of Irish heritage",
    ],
    "polack": [
        "offensive term",
        "Polish person",
        "person of Polish descent",
        "Eastern European person",
        "individual of Polish heritage",
    ],
    "greaseball": [
        "offensive term",
        "Italian person",
        "person of Italian descent",
        "Mediterranean person",
        "individual of Italian heritage",
    ],
    "dyke": [
        "offensive term",
        "lesbian",
        "homosexual woman",
        "same-sex attracted woman",
        "homophilic woman",
    ],
    "bastard": [
        "illegitimate",
        "difficult person",
        
        "unfortunate person",
        "unpleasant individual",
    ],
    "motherfucker": [
        
        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "obnoxious person",
    ],
    "fuckup": [
        
        "created a huge mess"
    ],
    "son of a bitch": [
        
        "inconsiderate person",
        "difficult person",
        "unpleasant individual",
        "obnoxious person",
    ],
    "cock sucker": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "ass wipe": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "fucking": ["extremely", "very", "really", "intensely", "remarkably"],
    "shithead": [
        "idiot",
        "fool",
        
        "inconsiderate person",
        "unintelligent person",
    ],
    "dickhead": [
        "idiot",
        "fool",
        
        "inconsiderate person",
        "unintelligent person",
    ],
    "twat": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "pussy": ["cat", "kitten", "coward", "weakling", "timid person"],
    "clit": [
        "clitoris",
        "female genitalia",
        "vulva",
        "intimate area",
        "anatomical feature",
    ],
    "ball sack": [
        "scrotum",
        "testicles",
        "male genitalia",
        "intimate area",
        "anatomical feature",
    ],
    "testicles": [
        "testes",
        "male reproductive organs",
        "gonads",
        "intimate area",
        "anatomical feature",
    ],
    "tits": ["breasts", "boobs", "bosom", "chest", "anatomical feature"],
    "boobs": ["breasts", "tits", "bosom", "chest", "anatomical feature"],
    "nipples": [
        "areola",
        "mammary papilla",
        "breast tip",
        "chest",
        "anatomical feature",
    ],
    "vagina": [
        "vulva",
        "female genitalia",
        "birth canal",
        "intimate area",
        "anatomical feature",
    ],
    "penis": [
        "male genitalia",
        "phallus",
        "organ",
        "intimate area",
        "anatomical feature",
    ],
    "ejaculate": [
        "semen",
        "sperm",
        "sexual fluid",
        "bodily fluid",
        "reproductive fluid",
    ],
    "orgasm": [
        "climax",
        "sexual peak",
        "sexual pleasure",
        "intense sensation",
        "culmination",
    ],
    "masturbate": [
        "self-pleasure",
        "self-stimulation",
        "manual stimulation",
        "intimate act",
        "private act",
    ],
    "jerk off": [
        "masturbate",
        "self-pleasure",
        "self-stimulation",
        "manual stimulation",
        "private act",
    ],
    "cum": ["semen", "sperm", "ejaculate", "sexual fluid", "reproductive fluid"],
    "fuckface": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "butthole": [
        "anus",
        "rectum",
        "posterior opening",
        "bodily opening",
        "anatomical feature",
    ],
    "anal": [
        "rectal",
        "posterior",
        "pertaining to the anus",
        "bodily opening",
        "anatomical region",
    ],
    "porn": [
        "pornography",
        "adult entertainment",
        "erotica",
        "sexually explicit material",
        "adult content",
    ],
    "porno": [
        "pornography",
        "adult entertainment",
        "erotica",
        "sexually explicit material",
        "adult content",
    ],
    "sex": [
        "intercourse",
        "sexual activity",
        "sexual relations",
        "intimacy",
        "physical intimacy",
    ],
    "sexist": [
        "gender biased",
        "gender discriminatory",
        "prejudiced against women",
        "biased against a gender",
        "gender inequitable",
    ],
    "racist": [
        "racially biased",
        "racially discriminatory",
        "prejudiced against a race",
        "biased against a race",
        "racially inequitable",
    ],
    "homophobic": [
        "anti-gay",
        "prejudiced against homosexuals",
        "biased against LGBTQ+",
        "intolerant of homosexuality",
        "homo-antagonistic",
    ],
    "xenophobic": [
        "anti-foreigner",
        "prejudiced against foreigners",
        "biased against immigrants",
        "intolerant of foreigners",
        "xeno-antagonistic",
    ],
    "bigot": [
        "intolerant person",
        "prejudiced person",
        "biased person",
        "narrow-minded person",
        "dogmatic individual",
    ],
    "slutty": ["promiscuous", "loose", "immoral", "sexually active", "unchaste"],
    "whoring": [
        "prostitution",
        "promiscuity",
        "commercial sex",
        "sexual exploitation",
        "sexual commerce",
    ],
    "pimp": [
        "procurer",
        "exploiter",
        "profiteer",
        "trafficker",
        "facilitator of exploitation",
    ],
    "whorehouse": [
        "brothel",
        "house of prostitution",
        "bawdy house",
        "red-light district",
        "establishment of commercial sex",
    ],
    "brothel": [
        "whorehouse",
        "house of prostitution",
        "bawdy house",
        "red-light district",
        "establishment of commercial sex",
    ],
    "prostitute": [
        "sex worker",
        "commercial sex worker",
        "streetwalker",
        "escort",
        "sex trade worker",
    ],
    "escort": [
        "companion",
        "social escort",
        "dating partner",
        "paid companion",
        "commercial companion",
    ],
    "hooker": [
        "prostitute",
        "sex worker",
        "streetwalker",
        "commercial sex worker",
        "sex trade worker",
    ],
    "harlot": ["prostitute", "whore", "loose woman", "immoral woman", "unchaste woman"],
    "sugar daddy": [
        "wealthy benefactor",
        "older partner",
        "financial supporter",
        "generous patron",
        "patron of companionship",
    ],
    "gold digger": [
        "materialistic person",
        "opportunistic person",
        "fortune hunter",
        "financially motivated person",
        "materially driven individual",
    ],
    "sugar baby": [
        "younger partner",
        "beneficiary",
        "recipient of support",
        "compensated companion",
        "recipient of patronage",
    ],
    "mistress": [
        "lover",
        "paramour",
        "extramarital partner",
        "secret partner",
        "clandestine partner",
    ],
    "gigolo": [
        "male escort",
        "paid companion",
        "male prostitute",
        "kept man",
        "male commercial companion",
    ],
    "jigaboo": [
        "offensive term",
        "black person",
        "African American",
        "person of African descent",
        "individual of African heritage",
    ],
    "coon": [
        "offensive term",
        "black person",
        "African American",
        "person of African descent",
        "individual of African heritage",
    ],
    "asshat": [ "fool", "idiot", "inconsiderate person", "bonehead"],
    "bugger": ["bother", "annoy", "inconvenience", "irritate", "disturb"],
    "bloody": ["very", "extremely", "really", "remarkably", "particularly"],
    "bollocks": ["nonsense", "rubbish", "fiddlesticks", "poppycock", "balderdash"],
    "buggered": ["tired", "exhausted", "worn out", "fatigued", "drained"],
    "choad": ["fool", "idiot",  "inconsiderate person", "obnoxious person"],
    "crikey": ["wow", "gosh", "jeez", "heck", "goodness"],
    "git": [
        "unpleasant person",
        
        "inconsiderate person",
        "difficult individual",
        "obnoxious person",
    ],
    "knob": ["fool", "idiot",  "inconsiderate person", "obnoxious person"],
    "minge": [
        "offensive term",
        "female genitalia",
        "private parts",
        "intimate area",
        "anatomical feature",
    ],
    "numpty": [
        "fool",
        "idiot",
        "simpleton",
        "unintelligent person",
        "naïve individual",
    ],
    "pillock": ["fool", "idiot",  "inconsiderate person", "obnoxious person"],
    "plonker": [
        "fool",
        "idiot",
        "simpleton",
        "unintelligent person",
        "naïve individual",
    ],
    "shag": [
        "intercourse",
        "sexual activity",
        "sexual relations",
        "intimacy",
        "physical intimacy",
    ],
    "tosser": [
        "offensive term",
        
        "inconsiderate person",
        "difficult person",
        "obnoxious person",
    ],
    "wanker": [
        "offensive term",
        
        "inconsiderate person",
        "difficult person",
        "obnoxious person",
    ],
    "bellend": [
        "offensive term",
        
        "inconsiderate person",
        "difficult person",
        "obnoxious person",
    ],
    "arse": ["rear", "buttocks", "inconsiderate person",  "stubborn person"],
    "bloody hell": [
        "unfortunate situation",
        "difficult time",
        "frustrating experience",
        "unpleasant ordeal",
        "trying period",
    ],
    "cunting": ["offensive", "unpleasant", "vile", "despicable", "abhorrent"],
    "minging": ["unpleasant", "disgusting", "revolting", "offensive", "nasty"],
    "slag": ["promiscuous", "loose", "immoral", "sexually active", "unchaste"],
    "tart": ["promiscuous", "loose", "immoral", "sexually active", "unchaste"],
    "randy": ["horny", "lustful", "lecherous", "lascivious", "salacious"],
    "munter": [
        "unattractive person",
        "ugly person",
        "homely person",
        "plain person",
        "unappealing individual",
    ],
    "mingebag": [
        "offensive term",
        "unpleasant person",
        "vile person",
        "despicable person",
        "abhorrent individual",
    ],
    "fuckwit": [
        "fool",
        "idiot",
        
        "inconsiderate person",
        "unintelligent person",
    ],
    "spunk": ["semen", "sperm", "ejaculate", "sexual fluid", "reproductive fluid"],
    "jizz": ["semen", "sperm", "ejaculate", "sexual fluid", "reproductive fluid"],
    "wank": [
        "masturbate",
        "self-pleasure",
        "self-stimulation",
        "manual stimulation",
        "private act",
    ],
    "sod off": ["leave", "depart", "go away", "scram", "get lost"],
    "twat waffle": [
        "offensive term",
        "stupid person",
        "inconsiderate person",
        "unpleasant individual",
        "obnoxious person",
    ],
}

hindi = {
    "aad": [
        "individual",
        "person",
    ],
    "aand": [
        "small thought",
        "brief idea",
    ],
    "bahenchod": [
        "unpleasant person",
        "rude individual",
    ],
    "behenchod": [
        "unpleasant person",
        "disrespectful individual",
    ],
    "bhenchod": [
        "rude person",
        "disrespectful individual",
    ],
    "bhenchodd": [
        "disagreeable person",
        "unpleasant individual",
    ],
    "b.c.": [
        "individual",
        "person",
    ],
    "bc": [
        "person",
        "individual",
    ],
    "bakchod": [
        "talkative person",
        "chatterbox",
    ],
    "bakchodd": [
        "talkative person",
        "chatterbox",
    ],
    "bakchodi": [
        "excessive talking",
        "chatter",
    ],
    "bevda": [
        "person who enjoys drinking",
        "drinker",
    ],
    "bewda": [
        "person who enjoys drinking",
        "drinker",
    ],
    "bevdey": [
        "frequent drinker",
        "habitual drinker",
    ],
    "bewday": [
        "person who enjoys drinking",
        "drinker",
    ],
    "bevakoof": [
        "naive person",
        "innocent individual",
    ],
    "bevkoof": [
        "innocent person",
        "naive individual",
    ],
    "bevkuf": [
        "uninformed person",
        "ignorant individual",
    ],
    "bewakoof": [
        "naive individual",
        "uninformed person",
    ],
    "bewkoof": [
        "naive person",
        "uninformed individual",
    ],
    "bhadua": [
        "unfortunate person",
        "disliked individual",
    ],
    "bhaduaa": [
        "unfortunate person",
        "disliked individual",
    ],
    "bhadva": [
        "disliked individual",
        "unfortunate person",
    ],
    "bhadvaa": [
        "disliked individual",
        "unfortunate person",
    ],
    "bhadwa": [
        "unfortunate individual",
        "disliked person",
    ],
    "bhadwaa": [
        "unfortunate person",
        "disliked individual",
    ],
    "bhosada": [
        "disagreeable person",
        "rude individual",
    ],
    "bhosda": [
        "unpleasant person",
        "rude individual",
    ],
    "bhosdaa": [
        "hostile individual",
        "disagreeable person",
    ],
    "bhosdike": [
        "rude person",
        "disrespectful individual",
    ],
    "bhonsdike": [
        "hostile individual",
        "disrespectful person",
    ],
    "bsdk": [
        "rude person",
        "disrespectful individual",
    ],
    "b.s.d.k": [
        "disrespectful person",
        "rude individual",
    ],
    "bhosdiki": [
        "unpleasant person",
        "hostile individual",
    ],
    "bhosdiwala": [
        "individual with negative attitude",
        "unpleasant person",
    ],
    "bhosdiwale": [
        "disagreeable individual",
        "unpleasant person",
    ],
    "bhosadchodal": [
        "unpleasant person",
        "disagreeable individual",
    ],
    "bhosadchod": [
        "unpleasant person",
        "disagreeable individual",
    ],
    "bhosadchodal": [
        "disrespectful individual",
        "hostile person",
    ],
    "babbe": [
        "person",
        "individual",
    ],
    "babbey": [
        "person",
        "individual",
    ],
    "bube": [
        "individual",
        "person",
    ],
    "bubey": [
        "individual",
        "person",
    ],
    "bur": [
        "unpleasant person",
        "disagreeable individual",
    ],
    "burr": [
        "unpleasant person",
        "disagreeable individual",
    ],
    "buurr": [
        "unpleasant person",
        "disagreeable individual",
    ],
    "buur": [
        "unpleasant person",
        "disrespectful individual",
    ],
    "charsi": [
        "person who consumes substances",
        "individual with addiction",
    ],
    "chooche": [
        "small individual",
        "petite person",
    ],
    "choochi": [
        "small person",
        "tiny individual",
    ],
    "chuchi": [
        "small person",
        "tiny individual",
    ],
    "chhod": [
        "leave",
        "depart",
    ],
    "chod": [
        "leave",
        "depart",
    ],
    "chodd": [
        "depart",
        "leave",
    ],
    "chudne": [
        "to stop",
        "to quit",
    ],
    "chudney": [
        "to stop",
        "to quit",
    ],
    "chudwa": [
        "person who quits",
        "individual who leaves",
    ],
    "chudwaa": [
        "person who stops",
        "individual who leaves",
    ],
    "chudwane": [
        "to stop",
        "to quit",
    ],
    "chudwaane": [
        "to stop",
        "to quit",
    ],
    "choot": [
        "error",
        "mistake",
    ],
    "chut": [
        "error",
        "mistake",
    ],
    "chute": [
        "mistake",
        "error",
    ],
    "chutia": [
        "person who makes mistakes",
        "individual who errs",
    ],
    "chutiya": [
        "person who makes a mistake",
        "individual who errs",
    ],
    "chutiye": [
        "person who errs",
        "individual who makes mistakes",
    ],
    "chuttad": [
        "person with flaws",
        "individual with weaknesses",
    ],
    "chutad": [
        "person with flaws",
        "individual with weaknesses",
    ],
    "dalaal": [
        "agent",
        "middleman",
    ],
    "dalal": [
        "agent",
        "intermediary",
    ],
    "dalle": [
        "individual in shady deals",
        "person involved in dealings",
    ],
    "dalley": [
        "person involved in shady dealings",
        "individual facilitating deals",
    ],
    "fattu": [
        "fearful person",
        "timid individual",
    ],
    "gadha": [
        "stubborn person",
        "individual with resistance",
    ],
    "gadhe": [
        "stubborn individual",
        "person who resists",
    ],
    "gadhalund": [
        "stubborn individual",
        "resistant person",
    ],
    "gaand": [
        "backside",
        "rear",
    ],
    "gand": [
        "backside",
        "rear",
    ],
    "gandu": [
        "uncooperative individual",
        "resistant person",
    ],
    "gandfat": [
        "person with shortcomings",
        "individual with flaws",
    ],
    "gandfut": [
        "individual with mistakes",
        "person with flaws",
    ],
    "gandiya": [
        "disagreeable person",
        "unpleasant individual",
    ],
    "gandiye": [
        "unpleasant person",
        "disagreeable individual",
    ],
    "goo": [
        "sticky substance",
        "slimy material",
    ],
    "gu": [
        "person",
        "individual",
    ],
    "gote": [
        "small group",
        "few individuals",
    ],
    "gotey": [
        "small group",
        "few people",
    ],
    "gotte": [
        "small group",
        "few individuals",
    ],
    "hag": [
        "elderly woman",
        "aged woman",
    ],
    "haggu": [
        "elderly person",
        "aged individual",
    ],
    "hagne": [
        "to lie",
        "to speak falsely",
    ],
    "hagney": [
        "to speak falsely",
        "to lie",
    ],
    "harami": [
        "immoral person",
        "dishonest individual",
    ],
    "haramjada": [
        "dishonest person",
        "immoral individual",
    ],
    "haraamjaada": [
        "immoral person",
        "dishonest individual",
    ],
    "haramzyada": [
        "dishonest individual",
        "immoral person",
    ],
    "haraamzyaada": [
        "dishonest individual",
        "immoral person",
    ],
    "haramjaade": [
        "dishonest individual",
        "immoral person",
    ],
    "haramzaade": [
        "dishonest individual",
        "immoral person",
    ],
    "haramkhor": [
        "dishonest person",
        "immoral individual",
    ],
    "haramkhor": [
        "dishonest individual",
        "immoral person",
    ],
}

def merge_dicts(*dicts):
    merged_dict = {}

    for d in dicts:
        for key, value in d.items():
            if key in merged_dict:
                # Append the new value to the existing list
                if value not in merged_dict[key]:  # To avoid duplicates
                    merged_dict[key].append(value)
            else:
                merged_dict[key] = [value]  # Initialize with a list

    return merged_dict


# Merging the dictionaries
final_dict = merge_dicts(
    bad_words_dict1, bad_words_dict2, bad_words_dict3, bad_words_dict4,
)

# Pretty-printing the result
# print(json.dumps(final_dict, indent=4))
